name: Behave

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: martinthomson/i-d-template:latest

    steps:
    - uses: actions/checkout@v1
    - name: Check environment
      run: |
        pwd
        ls
        env
